### ISSUE TITLE
GraphQL Operation Naming Convention

### ISSUE THREAD

**Issue by aq1018** [BuoySoftware/guides#51]
Since `graphql-codegen` puts everything in one file, there can be naming collisions unless we give some thoughts on how we name our queries, mutations, subscriptions, and fragments.

I don't really have any good idea on a convention, but would like to bring this up so we can avoid future maintenance issues. Ideas are welcome.

**Comment by rayfaddis** [comment]
Replying here for posterity (in addition to a few GH threads on different peoples PRs).

Current convention is for queries, mutations, and fragments filenames to match the respective GQL name. This allows a component and it's sub-components to define multiple queries/mutations/fragments without clashing and also keeps things more descriptive in general.
