### ISSUE TITLE
Do Not Overuse Generated GraphQL Types 

### ISSUE THREAD

**Issue by aq1018** [BuoySoftware/guides#53]
Example:

```ts
// ComponentA.tsx

import { useDonationQuery, DonationQueryResult } from 'generated';

// note that this is exported and used by other components
export type Donation = NonNullable<Get<DonationQueryResult, 'data.donation'>>;

export const ComponentA: React.FC = () => {
  // ...
}
```

```ts
// ComponentB.tsx
// This is a pure component, no business logic, only display logic

import { Donation }  from './ComponentA';

// Notice we are using `Donation` type from GraphQL generated types.
export interface ComponentBProps {
  donation: Donation;
};

export const ComponentB: React.FC<ComponentBProps> = ({ donation }) => {
 // ...
}
```

Notice that Component B is now closely coupled with Component A. If Component A changes the query, Component B will be broken. Another reason is that Component B should have its own prop type interface that contains what is needed for that component to render. It can be a (desirable) coincidence that what component B needs lines up with some graphql type, but the graphql type should not dictate Component B's programming interface.

A better way to implement component B would be:

```ts
// ComponentB.tsx
// This is a pure component, no business logic, only display logic

// this should reflect what is needed to render the component. `Donation` type just happen to match this interface as a coincidence. They are not in fact related.
export interface ComponentBProps {
  prop1: string;
  prop2: int;
};

export const ComponentB: React.FC<ComponentBProps> = ({ prop1, prop2 }) => {
 // ...
}
```

**Comment by rayfaddis** [comment]
I think this is something to be considerate of for sure. In general really, there should the caution of when tightly coupling certain things. Though for some direct child components I also think it is safe and even at times desired to ensure you are working with the exact type of object. Additionally if we always created new types we could get into situations of redefining the same thing in several places which creates a separate management issue.

@acostanzo I'm curious your thoughts on this one?

**Comment by acostanzo** [comment]
@rayfaddis I think you hit the nail on the head WRT to child components. I think we should be reusing the same type in that situation.

In the example above I wouldn't recommend exporting type Donation from ComponentA. Instead I would recommend importing from generated for both ComponentA and ComponentB.

Additionally you probably wouldn't be passing the whole shared object along unless you needed all or most of it. In the case where you only need some props, I wouldn't necessarily define the interface manually if the values come from the generated type of some data. Instead I would import the type from the generated file and explicitly "pick" the fields that the component needs.

**Comment by aq1018** [comment]
@acostanzo I love the usage of `Pick` idea. But still I think it's good to make the judgement call on whether the props are the same because you intend to couple them or they are by accident though.

**Comment by acostanzo** [comment]
@aq1018 I agree, we shouldn't use the type from another component or utility if its just because the interface is similar. However, I think it's OK and proper to leverage the types exported from generated files provided you are intentionally passing along data from the specific graphQL request's document that was used to define that type.

Generated types aside... With regards to your first example I agree its bad practice in this scenario where ComponentB is agnostic of ComponentA:
```
app/
  ComponentA/
    ComponentA.tsx
  ComponentB/
    ComponentB.tsx
```

But I feel OK with it in this scenario where ComponentB is intentionally coupled to ComponentA:
```
app/
  ComponentA/
    ComponentA.tsx
    ComponentB.tsx
```

**Comment by aq1018** [comment]
@acostanzo that makes perfect sense. Thanks!

**Comment by aq1018** [comment]
Should we close this?

**Comment by acostanzo** [comment]
Sounds good to me!
