### ISSUE TITLE
Standardize how we do feature specs when supporting parallel versions of features in Rails and React

### ISSUE THREAD

**Issue by Simonpedro** [BuoySoftware/guides#88]
So far I've seen three different ways in which we test the Rails implementation of a feature that already exists in React, and it'd be nice if the reach consensus on the preferred approach.

1. Copying and pasting all "React" specs for Rails, either [in the same spec file](https://github.com/BuoySoftware/BuoyRails/blob/2f074f1ec99fd1b7b8e0b32483c750f2c0fc7a3e/spec/features/processing/processing_donation_sample_spec.rb#L556) or [in a new one](https://github.com/BuoySoftware/BuoyRails/blob/1e7a870819cb32b29508a914201300f203c8675b/spec/features/donor_qualification/qualifying_donors_rails_spec.rb)

2. [Iterate two times over [true, false]](https://github.com/BuoySoftware/BuoyRails/blob/2f074f1ec99fd1b7b8e0b32483c750f2c0fc7a3e/packs/test_results/spec/features/review_results/review_results_spec.rb#L14)

3. [Use shared examples and use it twice, with the feature flag enabled and disabled](https://github.com/BuoySoftware/BuoyRails/blob/2f074f1ec99fd1b7b8e0b32483c750f2c0fc7a3e/spec/features/reception/donor_screening_spec.rb#L867-L877)

I think both 2) and 3) are superior to 1) since in 1) [there is more risk of missing coverage when copy and pasting the specs](https://www.notion.so/Root-Cause-Analysis-Unit-Eligibility-Status-modal-missed-on-Rails-conversion-10b3d71a923380428239d457126f7fa7). In 2) and 3) any missing coverage becomes more visible, as well as any future changes on the spec (because of new requirements). 

A nice side effect of approaches 2) and 3) is that it forces the developer to write specs from the user's point of view, relying more in accessible items like text, labels, legends, etc.

Lastly, I think 3) is superior to 2) since it's possible to run one branch (let's say the Rails one) and not the other.

**Comment by Simonpedro** [comment]
@dgalarza What you think of this?

**Comment by tute** [comment]
Reminder we discussed this in Slack here: https://buoy-software.slack.com/archives/CLF46S290/p1710945816631299?thread_ts=1710945105.946749&cid=CLF46S290. Option 2 messes up stacktraces on failures, so 3 is best I think!

**Comment by arzezak** [comment]
I’m also in favor of option 3.

**Comment by Simonpedro** [comment]
Done in https://github.com/BuoySoftware/guides/pull/92
